[workspace]
resolver = "2"
members = [ "benchmarking", "bits","dao", "metrics", "descent", "rp_forest", "utils", "r_descent", "r_descent","SISAP2025_experiments"]

[profile.release]
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = 'unwind'
incremental = false
codegen-units = 1