[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
rand_distr = "0.5.1"
rand_chacha = "0.9.0"
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
randperm-crt = "0.3.0"
